apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-management-api
spec:
  replicas: 3  # 副本数量
  selector:
    matchLabels:
      app: incident-management-api
  template:
    metadata:
      labels:
        app: incident-management-api
    spec:
      containers:
        - name: incident-management-api
          image: aqi2024/incident-management-api:latest  # 使用Docker Hub上的镜像
          ports:
            - containerPort: 8080
