apiVersion: v1
kind: Service
metadata:
  name: incident-management-service
spec:
  type: NodePort
  selector:
    app: incident-management-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30007  # 节点端口，配置后可通过此端口访问应用
