spring:
  datasource:
    url: jdbc:h2:mem:dbtest
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springfox:
  documentation:
    swagger:
      v2:
        path: /v2/ad-docs

logging:
  level:
    org:
        hibernate:
          SQL: DEBUG
          TYPE: TRACE
  access:
    enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有端点
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    enabled: true